services:
  postgres:
    image: 'postgres:latest'
    container_name: 'freelance-postgres'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
  rabbitmq:
    image: 'rabbitmq:management'
    container_name: 'freelance-rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}'
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}'
    ports:
      - '${RABBITMQ_PORT}:5672'
      - '15672:15672'

volumes:
  postgres_data: