services:
  postgres:
    image: 'postgres:latest'
    container_name: 'freelance-postgres'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
  rabbitmq:
    image: 'rabbitmq:management'
    container_name: 'freelance-rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}'
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}'
    ports:
      - '${RABBITMQ_PORT}:5672'
      - '15672:15672'
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freelance-backend
    ports:
      - "8081:${SERVER_PORT}"
    environment:
      - 'DB_URL=${DB_URL}'
      - 'DB_NAME=${DB_NAME}'
      - 'DB_USERNAME=${DB_USERNAME}'
      - 'DB_PASSWORD=${DB_PASSWORD}'
      - 'DB_PORT=${DB_PORT}'
      - 'RABBITMQ_USERNAME=${RABBITMQ_USERNAME}'
      - 'RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}'
      - 'RABBITMQ_PORT=${RABBITMQ_PORT}'
      - 'RABBITMQ_HOST=${RABBITMQ_HOST}'
      - 'RABBITMQ_EXCHANGE=${RABBITMQ_EXCHANGE}'
      - 'RABBITMQ_QUEUE=${RABBITMQ_QUEUE}'
      - 'RABBITMQ_ROUTING_KEY=${RABBITMQ_ROUTING_KEY}'
      - 'SERVER_PORT=${SERVER_PORT}'
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
    driver: local